# Generated by Django 4.2.11 on 2024-05-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='format',
        ),
    ]
